### ISSUE TITLE
Slow GVIM start up

### ISSUE THREAD

**Issue by oblitum** [hsanson/vim-android#36]
This is an spinoff of issue #33 and the same setup and debugging should apply. I've checked that when starting GVIM just by clicking its icon, it loads but gets stuck for quite a while processing something and I can't edit or do anything. Removing vim-android plugin solves the issue. Again, it relates with my home folder having android sdk folders, and I'm not sure why but the plugin just starts digging it. After GVIM is loaded my airline gets an Android section, although this is non-intentional since in truth there's no android project.

**Comment by hsanson** [comment]
The problem is that vim will try to find a gradle file as soon as you open a java/xml file and since you are in your home it will look all the way inside it. I need to find a better heuristic to determine when a project is a gradle project or an android project.

You can use these commands to find out what configuration files the plugin is finding.

    :echo gradle#findGradleFile()
    :echo android#findManifestFile()

**Comment by oblitum** [comment]
`:echo gradle#findGradleFile()` gives `/home/francisco/`, `:echo android:findManifestFile()` gives `/home/francisco/Documents/Projects/samples/android/BluetoothLeGatt/Application/src/main/AndroidManifest.xml`.

It manages to find this manifest at random, just because I'm at the home directory which contains `.android`, `.gradle` and other configuration files and folders.

**Comment by oblitum** [comment]
Repeating myself, there's NO android project at home directory. `.android` and `.gradle` folders were created by the android tools automatically at some point to store configurations.

**Comment by oblitum** [comment]
This issue is quite annoying since GVim/MacVim default directory when launching it up is ~ and anyone that have Android SDK and Gradle installed also have `.android` and `.gradle` directories at ~.

**Comment by hsanson** [comment]
This issue should be solved in latest master:

  1. The gradle and manifest file search only starts when opening a java or xml file.
       Simply starting vim/gvim in your home should not trigger these searches.
  2. If no build.gradle file is found the the plugin stops loading. You mention the gradle#findGradleFile() returns your home directory so the plugin should stop loading immediately.

**Comment by oblitum** [comment]
It's not solved. Just updated and clicked on GVIM icon, stuck on start & fan running loud.

**Comment by oblitum** [comment]
my airline is still tagged with "Android" on launch.

**Comment by oblitum** [comment]
Is there a commit reference of what should have fixed this?

**Comment by oblitum** [comment]
> 1. The gradle and manifest file search only starts when opening a java or xml file. Simply starting vim/gvim in your home should not trigger these searches.

Not true **if** `autocmd User AirlineAfterInit call GradleAirlineInit()` from `plugin/gradle.vim` is being called because airline is being initialized on every GVIM start.

**Comment by oblitum** [comment]
Just checked that putting `autocmd User AirlineAfterInit echoe "HELLO"` I get an error message upon GVIM start.

**Comment by oblitum** [comment]
> 2. If no build.gradle file is found the the plugin stops loading. You mention the gradle#findGradleFile() returns your home directory so the plugin should stop loading immediately.

```
Error detected while processing function gradle#airlineStatus[5]..android#glyph[1]..android#isAndroidProject[1]..android#findManifestFile:
line   12:
E605: Exception not caught: howdy ho!
``

**Comment by hsanson** [comment]
@oblitum you are correct.  I totally forgot about airline status that also checks for the AndroidManifest.xml to set the android icon.

Results that if the build.gradle file is not found then gradle#findGradleFile() method returns the home directory instead of an empty string as I expected. This is a result of how fnamemodify works.

Fixing this method to return empty string when the gradle file is not found stops the android#findManifestFile() from searching any further.

I hope this fixes the issue.
